AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda + IAM Role (code from S3 zip)

Parameters:
  ToDoTableName:
    Type: String
    Default: alucloud92-todo-table

  LambdaCodeBucket:
    Type: String
    Description: S3 bucket where the lambda zip is stored

  LambdaCodeKey:
    Type: String
    Description: S3 key (path) to the lambda zip (e.g. lambdas/todo-lambda.zip)

  LambdaCodeVersion:
    Type: String
    Description: Versioning, otherwise lamba function is not updating on deployment.

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoReadToDo
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                  - dynamodb:UpdateItem
                Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ToDoTableName}

  TodoLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ToDoTableName
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
        S3ObjectVersion: !Ref LambdaCodeVersion

Outputs:
  TodoLambdaArn:
    Value: !GetAtt TodoLambda.Arn
    Export:
      Name: alucloud92-lambdas-TodoLambdaArn

  TodoLambdaName:
    Value: !Ref TodoLambda
    Export:
      Name: alucloud92-lambdas-TodoLambdaName
